name: mkdocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stclaircounty/builder:latest
      volumes:
        - ${{ github.workspace }}:/workspace 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug
        run: |
          echo $PWD
          ls -lah
      - name: Configure Git Credentials
        uses: stclaircounty/builder@v1.0.4