name: mkdocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stclaircounty/builder:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        uses: stclaircounty/builder/.github/actions/build@v1.0.2